### ISSUE TITLE
twoSum方法缺陷

### ISSUE THREAD

**Issue by xiaoningtongxue** [xiaoyu2er/leetcode-js#1]

**Comment by xiaoningtongxue** [comment]
假若numbers中有两对的和满足target，只能求得一对数字的index

**Comment by NLLionel** [comment]
const twoSum = function(nums, target) {
   let targetNumIndexs = []
	    for(let i = 0, length = nums.length; length > i; i++) {
	    	for(let j = i + 1; length > j; j++) {
	    		if (nums[i] + nums[j] === target) targetNumIndexs.push(i, j)
	    	}
	    }
	    return targetNumIndexs	
	}

**Comment by xiaoyu2er** [comment]
@NLLionel 

题干有对这个的解释

> You may assume that each input would have exactly one solution
